// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repo/iface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Novodremov/subscribe-be/internal/domain"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockISubscriptionRepo is a mock of ISubscriptionRepo interface.
type MockISubscriptionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockISubscriptionRepoMockRecorder
}

// MockISubscriptionRepoMockRecorder is the mock recorder for MockISubscriptionRepo.
type MockISubscriptionRepoMockRecorder struct {
	mock *MockISubscriptionRepo
}

// NewMockISubscriptionRepo creates a new mock instance.
func NewMockISubscriptionRepo(ctrl *gomock.Controller) *MockISubscriptionRepo {
	mock := &MockISubscriptionRepo{ctrl: ctrl}
	mock.recorder = &MockISubscriptionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISubscriptionRepo) EXPECT() *MockISubscriptionRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockISubscriptionRepo) Create(ctx context.Context, in *domain.CreateSubscription) (*domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(*domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockISubscriptionRepoMockRecorder) Create(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockISubscriptionRepo)(nil).Create), ctx, in)
}

// Delete mocks base method.
func (m *MockISubscriptionRepo) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockISubscriptionRepoMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockISubscriptionRepo)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockISubscriptionRepo) Get(ctx context.Context, id uuid.UUID) (*domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockISubscriptionRepoMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockISubscriptionRepo)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockISubscriptionRepo) List(ctx context.Context, limit, offset int) ([]domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockISubscriptionRepoMockRecorder) List(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockISubscriptionRepo)(nil).List), ctx, limit, offset)
}

// TotalCost mocks base method.
func (m *MockISubscriptionRepo) TotalCost(ctx context.Context, userID *uuid.UUID, serviceName *string, startDate, endDate *time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TotalCost", ctx, userID, serviceName, startDate, endDate)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TotalCost indicates an expected call of TotalCost.
func (mr *MockISubscriptionRepoMockRecorder) TotalCost(ctx, userID, serviceName, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalCost", reflect.TypeOf((*MockISubscriptionRepo)(nil).TotalCost), ctx, userID, serviceName, startDate, endDate)
}

// TotalCount mocks base method.
func (m *MockISubscriptionRepo) TotalCount(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TotalCount", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TotalCount indicates an expected call of TotalCount.
func (mr *MockISubscriptionRepoMockRecorder) TotalCount(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalCount", reflect.TypeOf((*MockISubscriptionRepo)(nil).TotalCount), ctx)
}

// Update mocks base method.
func (m *MockISubscriptionRepo) Update(ctx context.Context, in *domain.UpdateSubscription) (*domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, in)
	ret0, _ := ret[0].(*domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockISubscriptionRepoMockRecorder) Update(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockISubscriptionRepo)(nil).Update), ctx, in)
}
