// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgenerated

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Subscription struct {
	ID          pgtype.UUID        `db:"id"`
	ServiceName string             `db:"service_name"`
	Price       int32              `db:"price"`
	UserID      pgtype.UUID        `db:"user_id"`
	StartDate   pgtype.Date        `db:"start_date"`
	EndDate     pgtype.Date        `db:"end_date"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
}
