// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgenerated

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSubscription(ctx context.Context, db DBTX, arg CreateSubscriptionParams) (*Subscription, error)
	DeleteSubscription(ctx context.Context, db DBTX, id pgtype.UUID) (int64, error)
	GetSubscription(ctx context.Context, db DBTX, id pgtype.UUID) (*Subscription, error)
	ListSubscriptions(ctx context.Context, db DBTX, arg ListSubscriptionsParams) ([]*Subscription, error)
	SubscriptionsTotalCost(ctx context.Context, db DBTX, arg SubscriptionsTotalCostParams) (int64, error)
	TotalSubscriptions(ctx context.Context, db DBTX) (int32, error)
	UpdateSubscription(ctx context.Context, db DBTX, arg UpdateSubscriptionParams) (*Subscription, error)
}

var _ Querier = (*Queries)(nil)
