// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package sqlcgenerated

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (service_name, price, user_id, start_date, end_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, service_name, price, user_id, start_date, end_date, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ServiceName string      `db:"service_name"`
	Price       int32       `db:"price"`
	UserID      pgtype.UUID `db:"user_id"`
	StartDate   pgtype.Date `db:"start_date"`
	EndDate     pgtype.Date `db:"end_date"`
}

func (q *Queries) CreateSubscription(ctx context.Context, db DBTX, arg CreateSubscriptionParams) (*Subscription, error) {
	row := db.QueryRow(ctx, createSubscription,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		err = fmt.Errorf("query CreateSubscription: %w", err)
	}
	return &i, err
}

const deleteSubscription = `-- name: DeleteSubscription :execrows
DELETE FROM subscriptions
WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, db DBTX, id pgtype.UUID) (int64, error) {
	result, err := db.Exec(ctx, deleteSubscription, id)
	if err != nil {
		return 0, fmt.Errorf("query DeleteSubscription: %w", err)
	}
	return result.RowsAffected(), nil
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at
FROM subscriptions
WHERE id = $1
`

func (q *Queries) GetSubscription(ctx context.Context, db DBTX, id pgtype.UUID) (*Subscription, error) {
	row := db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		err = fmt.Errorf("query GetSubscription: %w", err)
	}
	return &i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at
FROM subscriptions
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSubscriptionsParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListSubscriptions(ctx context.Context, db DBTX, arg ListSubscriptionsParams) ([]*Subscription, error) {
	rows, err := db.Query(ctx, listSubscriptions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, fmt.Errorf("query ListSubscriptions: %w", err)
	}
	defer rows.Close()
	var items []*Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("query ListSubscriptions: %w", err)
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("query ListSubscriptions: %w", err)
	}
	return items, nil
}

const subscriptionsTotalCost = `-- name: SubscriptionsTotalCost :one
SELECT COALESCE(SUM(
    price * 
    CASE 
        WHEN effective_end < effective_start THEN 0
        ELSE (
            (EXTRACT(YEAR FROM effective_end) - EXTRACT(YEAR FROM effective_start)) * 12 +
            (EXTRACT(MONTH FROM effective_end) - EXTRACT(MONTH FROM effective_start)) +
            1
        )
    END
), 0)::bigint AS total_cost
FROM (
    SELECT 
        price,
        -- Логика старта: если фильтр задан, берем максимум, иначе старт подписки
        CASE 
            WHEN $1::date IS NOT NULL 
                THEN GREATEST(start_date, $1::date)
            ELSE start_date
        END AS effective_start,

        -- Логика конца:
        -- 1. Определяем реальный конец подписки (если NULL, то считаем до сегодня или бесконечно?)
        -- 2. Определяем границу фильтра (если NULL, то берем реальный конец подписки)
        LEAST(
            COALESCE(end_date, CURRENT_DATE), -- Конец подписки (или сегодня)
            COALESCE($2::date, COALESCE(end_date, CURRENT_DATE)) -- Конец фильтра (или конец подписки/сегодня)
        ) AS effective_end

    FROM subscriptions
    WHERE 
        ($3::uuid IS NULL OR user_id = $3)
        AND ($4::text IS NULL OR service_name = $4)
        -- Фильтры работают только если переданы соответствующие даты
        AND ($2::date IS NULL OR start_date <= $2::date)
        AND ($1::date IS NULL OR end_date IS NULL OR end_date >= $1::date)
) AS calculated_periods
`

type SubscriptionsTotalCostParams struct {
	StartDate   pgtype.Date `db:"start_date"`
	EndDate     pgtype.Date `db:"end_date"`
	UserID      pgtype.UUID `db:"user_id"`
	ServiceName *string     `db:"service_name"`
}

func (q *Queries) SubscriptionsTotalCost(ctx context.Context, db DBTX, arg SubscriptionsTotalCostParams) (int64, error) {
	row := db.QueryRow(ctx, subscriptionsTotalCost,
		arg.StartDate,
		arg.EndDate,
		arg.UserID,
		arg.ServiceName,
	)
	var total_cost int64
	err := row.Scan(&total_cost)
	if err != nil {
		err = fmt.Errorf("query SubscriptionsTotalCost: %w", err)
	}
	return total_cost, err
}

const totalSubscriptions = `-- name: TotalSubscriptions :one
SELECT COUNT(*)::int AS total
FROM subscriptions
`

func (q *Queries) TotalSubscriptions(ctx context.Context, db DBTX) (int32, error) {
	row := db.QueryRow(ctx, totalSubscriptions)
	var total int32
	err := row.Scan(&total)
	if err != nil {
		err = fmt.Errorf("query TotalSubscriptions: %w", err)
	}
	return total, err
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET
    service_name = COALESCE($2, service_name),
    price = COALESCE($3, price),
    start_date = COALESCE($4, start_date),
    end_date = COALESCE($5, end_date),
    updated_at = NOW()
WHERE id = $1
RETURNING id, service_name, price, user_id, start_date, end_date, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	ID          pgtype.UUID `db:"id"`
	ServiceName string      `db:"service_name"`
	Price       int32       `db:"price"`
	StartDate   pgtype.Date `db:"start_date"`
	EndDate     pgtype.Date `db:"end_date"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, db DBTX, arg UpdateSubscriptionParams) (*Subscription, error) {
	row := db.QueryRow(ctx, updateSubscription,
		arg.ID,
		arg.ServiceName,
		arg.Price,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		err = fmt.Errorf("query UpdateSubscription: %w", err)
	}
	return &i, err
}
