// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package sqlcgenerated

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (service_name, price, user_id, start_date, end_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, service_name, price, user_id, start_date, end_date, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ServiceName string      `db:"service_name"`
	Price       int32       `db:"price"`
	UserID      pgtype.UUID `db:"user_id"`
	StartDate   pgtype.Date `db:"start_date"`
	EndDate     pgtype.Date `db:"end_date"`
}

func (q *Queries) CreateSubscription(ctx context.Context, db DBTX, arg CreateSubscriptionParams) (*Subscription, error) {
	row := db.QueryRow(ctx, createSubscription,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		err = fmt.Errorf("query CreateSubscription: %w", err)
	}
	return &i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions
WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, db DBTX, id pgtype.UUID) error {
	_, err := db.Exec(ctx, deleteSubscription, id)
	if err != nil {
		return fmt.Errorf("query DeleteSubscription: %w", err)
	}
	return nil
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at
FROM subscriptions
WHERE id = $1
`

func (q *Queries) GetSubscription(ctx context.Context, db DBTX, id pgtype.UUID) (*Subscription, error) {
	row := db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		err = fmt.Errorf("query GetSubscription: %w", err)
	}
	return &i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at
FROM subscriptions
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSubscriptionsParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListSubscriptions(ctx context.Context, db DBTX, arg ListSubscriptionsParams) ([]*Subscription, error) {
	rows, err := db.Query(ctx, listSubscriptions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, fmt.Errorf("query ListSubscriptions: %w", err)
	}
	defer rows.Close()
	var items []*Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("query ListSubscriptions: %w", err)
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("query ListSubscriptions: %w", err)
	}
	return items, nil
}

const listSubscriptionsFiltered = `-- name: ListSubscriptionsFiltered :many
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at
FROM subscriptions
WHERE
    ($1::uuid IS NULL OR user_id = $1)
    AND ($2::text IS NULL OR service_name = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListSubscriptionsFilteredParams struct {
	Column1 pgtype.UUID `db:"column_1"`
	Column2 string      `db:"column_2"`
	Limit   int32       `db:"limit"`
	Offset  int32       `db:"offset"`
}

func (q *Queries) ListSubscriptionsFiltered(ctx context.Context, db DBTX, arg ListSubscriptionsFilteredParams) ([]*Subscription, error) {
	rows, err := db.Query(ctx, listSubscriptionsFiltered,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, fmt.Errorf("query ListSubscriptionsFiltered: %w", err)
	}
	defer rows.Close()
	var items []*Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("query ListSubscriptionsFiltered: %w", err)
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("query ListSubscriptionsFiltered: %w", err)
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET
    service_name = COALESCE($2, service_name),
    price = COALESCE($3, price),
    start_date = COALESCE($4, start_date),
    end_date = COALESCE($5, end_date),
    updated_at = NOW()
WHERE id = $1
RETURNING id, service_name, price, user_id, start_date, end_date, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	ID          pgtype.UUID `db:"id"`
	ServiceName string      `db:"service_name"`
	Price       int32       `db:"price"`
	StartDate   pgtype.Date `db:"start_date"`
	EndDate     pgtype.Date `db:"end_date"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, db DBTX, arg UpdateSubscriptionParams) (*Subscription, error) {
	row := db.QueryRow(ctx, updateSubscription,
		arg.ID,
		arg.ServiceName,
		arg.Price,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		err = fmt.Errorf("query UpdateSubscription: %w", err)
	}
	return &i, err
}
